### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by txomin13** [geodynamics/autoconf_cig#19]
I would like to use modified versions of the m4 scripts in this repository for another project.
However, I am not sure what license does apply to them.

From https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license, I learned the following:

> You're under no obligation to choose a license. **However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work**. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

Is this use intended?

**Comment by knepley** [comment]
This is essentially the BSD license. There is a lot of online documentation about use.

**Comment by txomin13** [comment]
Thanks for clarifying! 
I would still suggest to add this license to the repository or at least add a link to it.
